<?php
/*
 * Plugin Name: Remove Canonical URLs
 * Description: A plugin which removes the canonical urls generated by WordPress and/or Yoast SEO.
 * Author: Gloomic
 * Version: 1.0
 * Author URI: https://gloomycorner.com
 * License: GPLv2
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 */

if ( ! defined( 'WPINC' ) ) {
    die( 'No direct access.' );
}

function no_canonical_url () {
    return NULL;
}

add_action( 'get_canonical_url', 'no_canonical_url' );
add_filter( 'wpseo_canonical', 'no_canonical_url' );
